import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // Login styles
  container: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: "center",
  },
  headerWrap: {
    marginBottom: 32,
    alignItems: "center",
  },
  logoContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#0b1220",
    borderWidth: 2,
    borderColor: "#22c55e",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  brand: {
    color: "#e2e8f0",
    fontSize: 28,
    fontWeight: "700",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  subtitle: {
    color: "#22c55e",
    marginTop: 4,
    fontSize: 16,
    fontWeight: "500",
    textAlign: "center",
  },
  loginText: {
    color: "#94a3b8",
    marginTop: 8,
    fontSize: 14,
    textAlign: "center",
  },
  card: {
    backgroundColor: "#0b1220",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  inputWrap: {
    marginBottom: 14,
    backgroundColor: "#0a0f1a",
    borderWidth: 1,
    borderColor: "#1e293b",
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    height: 48,
  },
  inputIcon: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    color: "#e2e8f0",
    fontSize: 15,
  },
  eyeBtn: {
    padding: 4,
  },
  errorText: {
    color: "#fca5a5",
    marginBottom: 8,
    marginTop: -2,
  },
  cta: {
    marginTop: 4,
  },
  ctaGradient: {
    height: 50,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  ctaContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  ctaIcon: {
    marginRight: 8,
  },
  ctaText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  // Admin dashboard styles
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchInput: {
    flex: 1,
    backgroundColor: "#0b1220",
    borderRadius: 24,
    height: 40,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#1f2937",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchPlaceholder: {
    color: "#94a3b8",
    marginLeft: 6,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#2563eb",
    alignItems: "center",
    justifyContent: "center",
  },
  locationLabel: {
    color: "#94a3b8",
    marginTop: 12,
    fontSize: 12,
  },
  locationValue: {
    color: "#e2e8f0",
    fontWeight: "600",
  },
  curvedPanelWrap: {
    paddingHorizontal: 12,
    marginTop: 16,
  },
  curvedPanel: {
    backgroundColor: "#0b1220",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  gridRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  featureItem: {
    alignItems: "center",
    flex: 1,
  },
  featureIconWrap: {
    backgroundColor: "#e2e8f0",
    borderRadius: 14,
    padding: 12,
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
  },
  featureLabel: {
    color: "#e2e8f0",
    marginTop: 8,
    fontSize: 12,
  },
  sectionTitle: {
    color: "#e2e8f0",
    fontWeight: "700",
    fontSize: 16,
    marginBottom: 12,
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
  },
  activityName: {
    color: "#e2e8f0",
    flex: 1,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "600",
  },
  viewText: {
    color: "#60a5fa",
    fontSize: 12,
  },
  cardsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  quickCard: {
    width: "48%",
    backgroundColor: "#0b1220",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1f2937",
    marginTop: 10,
    overflow: "hidden",
  },
  quickThumb: {
    height: 80,
    backgroundColor: "#ef4444",
  },
  quickTitle: {
    color: "#e2e8f0",
  },
  quickFab: {
    position: "absolute",
    right: 8,
    bottom: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#f59e0b",
    alignItems: "center",
    justifyContent: "center",
  },
  // User Dashboard styles
  userHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  welcomeText: {
    color: "#94a3b8",
    fontSize: 14,
  },
  userName: {
    color: "#e2e8f0",
    fontSize: 20,
    fontWeight: "700",
    marginTop: 2,
  },
  logoutBtn: {
    padding: 8,
  },
  userCard: {
    backgroundColor: "#0b1220",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  cardTitle: {
    color: "#e2e8f0",
    fontSize: 16,
    fontWeight: "600",
  },
  dropdownContainer: {
    marginBottom: 12,
  },
  label: {
    color: "#94a3b8",
    fontSize: 13,
    marginBottom: 6,
  },
  dropdown: {
    backgroundColor: "#0a0f1a",
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1e293b",
  },
  dropdownText: {
    color: "#e2e8f0",
    fontSize: 14,
  },
  statusRow: {
    flexDirection: "row",
    gap: 10,
  },
  statusBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#0a0f1a",
    borderWidth: 1,
    borderColor: "#1e293b",
    alignItems: "center",
  },
  statusBtnActive: {
    backgroundColor: "#22c55e",
    borderColor: "#22c55e",
  },
  statusBtnText: {
    color: "#e2e8f0",
    fontSize: 14,
    fontWeight: "500",
  },
  statusBtnTextActive: {
    color: "#ffffff",
  },
  actionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  actionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  actionText: {
    color: "#e2e8f0",
    fontSize: 14,
  },
  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 12,
  },
  quickActionBtn: {
    width: "48%",
    backgroundColor: "#0b1220",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  quickActionText: {
    color: "#e2e8f0",
    fontSize: 12,
    marginTop: 8,
    textAlign: "center",
  },
  // List styles
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  listTitle: {
    color: "#e2e8f0",
    fontSize: 14,
    fontWeight: "600",
  },
  listSub: {
    color: "#94a3b8",
    fontSize: 12,
    marginTop: 2,
  },
  listDesc: {
    color: "#94a3b8",
    fontSize: 12,
    marginTop: 6,
  },
  progressPill: {
    backgroundColor: "#065f46",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  progressText: {
    color: "#34d399",
    fontWeight: "700",
  },
  // User dashboard form styles
  dropdownMenu: {
    backgroundColor: "#0a0f1a",
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#1e293b",
    maxHeight: 200,
  },
  dropdownItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  dropdownItemText: {
    color: "#e2e8f0",
    fontSize: 14,
  },
  textInput: {
    backgroundColor: "#0a0f1a",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#1e293b",
    color: "#e2e8f0",
    fontSize: 14,
    marginTop: 8,
    textAlignVertical: "top",
  },
  numberInput: {
    backgroundColor: "#0a0f1a",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#1e293b",
    color: "#e2e8f0",
    fontSize: 18,
    fontWeight: "600",
    flex: 1,
    marginRight: 8,
  },
  progressInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  submitBtn: {
    backgroundColor: "#22c55e",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginTop: 24,
  },
  submitBtnText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  progressBarContainer: {
    height: 6,
    backgroundColor: "#0a0f1a",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressBar: {
    height: 6,
    borderRadius: 3,
  },
});
